settings:
  title: 'Status Page'
  url: 'https://f1.vvwv.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 3 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Jsondoc # unique identifier
    name: is.gd/Jsondoc
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://is.gd/Jsondoc' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: www-cloudflare-com
    name: rebrand.ly/oooooo
    description: 'Built for anything connected to the Internet.'
    url: 'https://rebrand.ly/ooooo'
    method: GET
    expectStatus: 200

  - id: i----i
    name: i----i.firebaseio.com
    url: 'https://i----i.firebaseio.com/.json'
    method: GET
    expectStatus: 200
