name = "f1"
workers_dev = true
account_id = "0de3674adef884f16d5803ba28ee6e13"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"

[[kv-namespaces]]
binding = "KV_STATUS_PAGE"
id = "8dabce9f99434b4498950d98e8b485bc"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"
entry-point = "./"


